### ISSUE TITLE
How do file descriptors notify the OS that it (FD) is ready to be operated on?

### ISSUE THREAD

**Issue by curiousdweller** [cfsamson/book-exploring-epoll-kqueue-iocp#10]
I have a decent understanding on how to use epoll but I haven't figured out how the layer beneath works. Lets say a list of 10 file descriptors are being waited on using an epoll_wait cll. Now a socket has some data and should be put into the ready state. How does an OS know to move it into the ready state (thus returning from the blocking epoll_wait)?

**Comment by curiousdweller** [comment]
For any future reader that might have a similar question, this is implemented using wait queue
[](http://www.science.unitn.it/~fiorella/guidelinux/tlk/node122.html)
[For more on Semaphores](https://pages.cs.wisc.edu/~remzi/OSTEP/threads-sema.pdf)

**Comment by cfsamson** [comment]
Sorry for the late reply, and @curiousdweller hopefully answered your question. 

To add a more context, I can recommend taking a look at another chapter I have written that tries to explain more in detail what happens when you wait for an event: https://cfsamson.github.io/book-exploring-async-basics/4_interrupts_firmware_io.html. I guess chapters 3, 4, 5 and 6 could be of interest as well.
